// src/constants/errorCodes.const.js
const ERROR_CODES = {
    BAD_REQUEST: "BAD_REQUEST",
    UNAUTHORIZED: "UNAUTHORIZED",
    NOT_FOUND: "NOT_FOUND",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    FORBIDDEN: "FORBIDDEN",
    CONFLICT: "CONFLICT",
    UNEXPECTED_ERROR: "UNEXPECTED_ERROR",
};

export default ERROR_CODES;
